---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: atlas-whitelister
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-lister
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: atlas-whitelister-lists-nodes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-lister
subjects:
- kind: ServiceAccount
  name: atlas-whitelister
