---
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: atlas-whitelister
spec:
  concurrencyPolicy: "Forbid"
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          restartPolicy: 'Never'
          serviceAccountName: atlas-whitelister
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 10
                preference:
                  matchExpressions:
                  - key: priority
                    operator: In
                    values:
                    - noncritical
          $TOLERATE_NONCRITICAL_ALL_ENVIRONMENTS
          containers:
          - name: atlas-whitelister
            image: eu.gcr.io/boclips-prod/boclips/atlas-whitelister:${VERSION}
            envFrom:
            - secretRef:
                name: atlas-whitelister
            resources:
              requests:
                cpu: 1m
                memory: 20Mi
              limits:
                cpu: 10m
                memory: 20Mi
